dbtdiary/accounts/urls.py
from __future__ import absolute_import

from django.conf.urls import patterns, url
from . import views as account_views

urlpatterns = patterns('',
  
	url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', account_views.logout_user, name='logout'),
    url(r'^register/$', account_views.register, name='register'),
   
	url(r'^account/reset/$','django.contrib.auth.views.password_reset', name='reset'),
    url(r'^account/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$','django.contrib.auth.views.password_reset_confirm', name='auth_password_reset_confim',),
    url(r'^account/reset/done/$','django.contrib.auth.views.password_reset_complete', name='reset-done'),
)

dbtdiary/diary/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('dbtdiary.diary.views',
    url(r'^$', 'index', name='index'),
    url(r'^about/$', 'about', name="about"),
    url(r'^contact/$', 'contact', name="contact"),
    url(r'^submit/$', 'submit', name='submit'),
    url(r'^summary/month/$', 'month_summary', name='month_summary'),
    url(r'^summary/year/$', 'year_summary', name='year_summary'),
    url(r'^summary/$', 'summary', name='summary'),
    url(r'^browse/$', 'browse', name='browse'),
    url(r'^diary/(?P<diary_id>\d*)/$', 'diary', name="diary"),
    url(r'^edit/(?P<diary_id>\d*)/$', 'edit', name="edit"),
    url(r'^delete/(?P<diary_id>\d*)/$', 'delete', name="delete"), 
)

dbtdiary/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from django.contrib.sitemaps import Sitemap, GenericSitemap, FlatPageSitemap


admin.autodiscover()

sitemaps = {
	'flatpages': FlatPageSitemap,
}

urlpatterns = patterns('',
   
    url(r'', include('dbtdiary.diary.urls', namespace='diary')),
    url(r'', include('dbtdiary.accounts.urls', namespace='accounts')),
    
    #legal junk
    url(r'^terms/$', direct_to_template, {"template": "terms.html"}, name="terms-of-use"),
    url(r'^privacy/$', direct_to_template, {"template": "privacy.html"}, name="privacy-policy"),
    
	#Admin
    url(r'^admin/', include(admin.site.urls)),
    
    
    
    #sitemap
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    
    #Serve Static content
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    }),
)

dbtdiary/accounts/forms.py
from django import forms
from django.utils.translation import ugettext, ugettext_lazy as _

from django.contrib.auth.models import User

class UserCreationForm(forms.ModelForm):
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
    }
    username = forms.RegexField(label=_("Username"), max_length=30,
        regex=r'^[\w-]+$')
    password = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

dbtdiary/diary/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import RadioSelect, CheckboxSelectMultiple
from .models import UsedSkills, Diary

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea(attrs={'class':'input-block-level',}))
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

class DiaryForm(forms.ModelForm):

	class Meta:
		model = Diary
		exclude = ('user', 'time', 'mood')
		widgets = {
			
			'urge_suicide': forms.RadioSelect(),
			'urge_sh': forms.RadioSelect(),
		  	'used_skills': forms.CheckboxSelectMultiple(),
			'pain': forms.RadioSelect(),
			'sad': forms.RadioSelect(),
			'shame': forms.RadioSelect(),
			'anger': forms.RadioSelect(),
			'fear': forms.RadioSelect(),
			'disgust': forms.RadioSelect(),
			'jealousy': forms.RadioSelect(),
			'guilt': forms.RadioSelect(),
			'agitation': forms.RadioSelect(),
			'joy': forms.RadioSelect(),
            'happy': forms.RadioSelect(),
            'content': forms.RadioSelect(),
            'calm': forms.RadioSelect(),
            'grateful': forms.RadioSelect(),
            'excitement': forms.RadioSelect(),
            'optimism': forms.RadioSelect(),
            'hope': forms.RadioSelect(),
            'confidence': forms.RadioSelect(),
            'notes': forms.Textarea(attrs={'class':'input-block-level'})
		}

 
class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=False)
 
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
 
    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

dbtdiary/accounts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.models import User
from django.template.response import TemplateResponse
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core import cache

from .forms import UserCreationForm

def register(request):
    if not settings.ALLOW_NEW_REGISTRATIONS:
        messages.error(request, "The admin of this service is not "
                                "allowing new registrations.")
        return HttpResponseRedirect(reverse('aggregator:index'))
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Thanks for registering. You are now logged in.')
            new_user = authenticate(username=request.POST['username'], password=request.POST['password'])
            login(request, new_user)
            return HttpResponseRedirect(reverse('diary:index'))
    else:
        form = UserCreationForm()

    return TemplateResponse(request, 'registration/registration_form.html', {'form': form})


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, 'You have successfully logged out.')
    return HttpResponseRedirect(reverse('diary:index'))

dbtdiary/diary/views.py
from django.template.response import TemplateResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.conf import settings
from django.shortcuts import render_to_response, render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import DiaryForm, UserCreateForm, ContactForm
from .models import Diary, User
import datetime

def index(request, username=None):
    # Displays the homepage
    if request.user.is_authenticated():
        diaries = Diary.objects.filter(user=request.user).order_by('-time')[:10]
        ctx = {'diaries' : diaries}
        template = 'diary/index.html'
    else:
        template = 'diary/welcome.html'
        ctx = {}    
    return render(request, template, ctx)

def about(request):
    c = {}
    all_users = User.objects.all()
    total_user_count = all_users.count()
    active_user_count = all_users.filter(userprofile__active=True).count()
    diaries = Diary.objects.all()
    diary_count = diaries.count()
    diaries_per_day = {}
    for diary in diaries:
        day = datetime.date(diary.time.year, diary.time.month, diary.time.day)
        if day in diaries_per_day.keys():
            diaries_per_day[day] += 1
        else:
            diaries_per_day[day] = 1
    c = {'user_count': total_user_count, 'diary_count': diary_count, 
         'active_users': active_user_count, 'diaries_per_day': diaries_per_day}
    return render(request, 'about.html', c)

def _calc_mood(diary):
    negative = 0.0
    positive = 0.0
    total = 0.0
    negative = diary.pain/5.0 + diary.sad/5.0 + diary.anger/5.0 + diary.fear/5.0 + diary.disgust/5.0 + diary.jealousy/5.0 + diary.guilt/5.0 + diary.agitation/5.0 + diary.shame/5.0
    positive = diary.joy/5.0 + diary.happy/5.0 + diary.content/5.0 + diary.calm/5.0 + diary.grateful/5.0 + diary.excitement/5.0 + diary.hope/5.0 + diary.confidence/5.0 + diary.optimism/5.0
    total = positive - negative
    return total

@login_required
def submit(request):
    form = DiaryForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            entry = form.save(commit=False)
            entry.user = request.user
            entry.mood = _calc_mood(entry)
            entry.save()
            form.save_m2m()
            messages.success(request, 'New entry successfully created.')
            return HttpResponseRedirect(reverse('diary:index'))
        else:
            messages.error(request, 'Did not pass validation! Please correct the errors below.')
    else:
        form = DiaryForm()
    c = {'form': form, 'adding': True}
    return TemplateResponse(request, 'diary/form.html', c)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user  = form.save()
            messages.success(request, 'Thank you for registering, you can now '
                                      'login.')
            return HttpResponseRedirect(reverse('diary:login'))
    else:
        form = UserCreationForm()

    return TemplateResponse(request, 'accounts/register.html', {'form': form})


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, 'You have successfully logged out.')
    return HttpResponseRedirect(reverse('diary:index'))

@login_required
def summary(request):
    return summary_helper(request, 7, 'diary/summary.html')

@login_required
def month_summary(request):
    return summary_helper(request, 30, 'diary/month_summary.html')

@login_required
def year_summary(request):
    return summary_helper(request, 365.0, 'diary/year_summary.html')

@login_required
def summary_helper(request, days, template):
    c = {}
    now = datetime.datetime.now()
    days_ago = datetime.timedelta(days=days)
    past = now - days_ago
    diaries = Diary.objects.filter(user=request.user, time__gte=past)
    skills_counts = {}
    for diary in diaries:
        skills = diary.used_skills.all().values_list('description', flat=True)
        for skill in skills:
            if skill in skills_counts:
                skills_counts[skill] += 1
            else:
                skills_counts[skill] = 1
    page_type = request.GET.get('type')
    if page_type == 'desktop':
        c['desktop'] = True
    c['diaries'] = diaries.order_by('time')
    c['reverse'] = diaries.order_by('-time')
    c['skills'] = skills_counts
    return TemplateResponse(request, template, c)  

@login_required
def browse(request):
    diaries = Diary.objects.filter(user=request.user).order_by('-time')
    paginator = Paginator(diaries, 25.0) # Show 25.0 diaries per page
    page = request.GET.get('page')
    try:
        diaries = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        diaries = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        diaries = paginator.page(paginator.num_pages)
    c = {"diaries" : diaries}
    return TemplateResponse(request, 'diary/browse.html', c)

@login_required
def diary(request, diary_id):
    diary = get_object_or_404(Diary, id=diary_id, user=request.user)
    skills = diary.used_skills.all().values_list('description', flat=True)
    return TemplateResponse(request, 'diary/diary.html', {'diary': diary, 'skills': skills})


@login_required
def delete(request, diary_id):
    #I wanted a way to delete old test entries.
    #It wlll be the last update I make to the code. 
    #I didnt add a public link anywhere to the site. You can decide if you want to let people know or not.
    diary = get_object_or_404(Diary, pk=diary_id, user=request.user)
    if request.method == 'POST':
        diary.delete()
        messages.success(request, 'Diary deleted.')
        return redirect('diary:index')
    return render(request, 'diary/delete-confirm.html', {'diary': diary})


@login_required
def edit(request, diary_id):
    diary = get_object_or_404(Diary, id=diary_id, user=request.user)
    form = DiaryForm(request.POST or None, instance=diary)
    if request.method == 'POST':
        if form.is_valid():
            entry = form.save(commit=False)
            entry.user = request.user
            entry.mood = _calc_mood(entry)
            entry.save()
            form.save_m2m()
            messages.success(request, 'Entry successfully saved.')
            return HttpResponseRedirect(reverse('diary:index'))
        else:
            messages.error(request, 'Did not pass validation! Please correct the errors below.')
    c = {'form': form, 'adding': False}
    return TemplateResponse(request, 'diary/form.html', c)

def contact(request):
    if request.method == 'POST': # If the form has been submitted...
        form = ContactForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['marie@violetco.de']
            if cc_myself:
                recipients.append(sender)

            from django.core.mail import send_mail
            send_mail(subject, message, sender, recipients)
            messages.success(request, 'Your message has been sent successfully. Thanks!')
            return HttpResponseRedirect('/') # Redirect after POST
    else:
        form = ContactForm() # An unbound form

    return render(request, 'diary/contact.html', {
        'form': form,
    })

dbtdiary/templates/diary/browse.html
{% extends 'base.html' %}

{% block content %}

<h2 class="heading">Previous Diaries</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Weekday</th>
            <th>Date</th>
            <th>Time</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
    {% for diary in diaries %}
        <tr>
            <td><a href="/diary/{{diary.id}}">{{diary.time|date:"l"}}</a></td>
            <td><a href="/diary/{{diary.id}}">{{diary.time|date:"F jS, Y"}}</a></td>
            <td><a href="/diary/{{diary.id}}">{{diary.time|date:"g:i a"}}</a></td>
            <td><a href="/edit/{{diary.id}}"><i class="icon-edit"></i></a></td>
            <td><a href="/delete/{{diary.id}}"><i class="icon-trash"></i></a></td>
        </tr>
    {% empty %}
        <tr><td>No previous diaries. You should <a href="/submit">fill one out</a>?</td></tr>
    {% endfor %}
    </tbody>
</table>

<div class="pagination row-fluid">
    <div class="span4">
        {% if diaries.has_previous %}
            <a href="?page={{ diaries.previous_page_number }}">Earlier Diaries</a>
        {% endif %}
    </div>
    <div class="span4">
        <span class="current">
            Page {{ diaries.number }} of {{ diaries.paginator.num_pages }}.
        </span>
    </div>
    <div class="span4">
        {% if diaries.has_next %}
            <a href="?page={{ diaries.next_page_number }}">Older Diaries</a>
        {% endif %}
    </div>
</div>

{% endblock %}

dbtdiary/templates/diary/charts.html
{% if diaries %}
    <h3 class="heading">Used Skills</h3>
    <div id="skills_chart"></div>
    <h3 class="heading">Urges</h3>
    {% if desktop %}
    <div id='mobile_urge_chart' class="hidden"></div>
    <div id='urge_chart' style='width: 900px; height: 300px;'></div> 
    {% else %}
    <div id='mobile_urge_chart' class="hidden-desktop"></div>
    <div id='urge_chart' style='width: 900px; height: 300px;' class="visible-desktop"></div> 
    {% endif %}
    <h3 class="heading">Mood</h3>
    {% if desktop %}
    <div id="mobile_mood_chart" class="hidden"></div>
    <div id="mood_chart" sytle='width: 900px; height: 300px;'></div>
    {% else %}
    <div id="mobile_mood_chart" class="hidden-desktop"></div>
    <div id="mood_chart" sytle='width: 900px; height: 300px;' class="visible-desktop"></div>
    {% endif %}
    <h3 class="heading">Emotions</h3>
    <h4 class="heading">Negative Emotions</h4>
    {% if desktop %}
    <ul class="nav nav-tabs" id="neg_emotion_tabs">
    {% else %}
    <ul class="nav nav-tabs visible-desktop" id="neg_emotion_tabs">
    {% endif %}
        <li><a href="#all" data-toggle="tab">All</a></li>
        <li><a href="#pain" data-toggle="tab" id="pain-tab">Pain</a></li>
        <li><a href="#sadness" data-toggle="tab" id="sad-tab">Sadness</a></li>
        <li><a href="#shame" data-toggle="tab" id="shame-tab">Shame</a></li>
        <li><a href="#anger" data-toggle="tab" id="anger-tab">Anger</a></li>
        <li><a href="#fear" data-toggle="tab" id="fear-tab">Fear</a></li>
        <li><a href="#disgust" data-toggle="tab" id="disgust-tab">Disgust</a></li>
        <li><a href="#jealousy" data-toggle="tab" id="jealousy-tab">Jealousy</a></li>
        <li><a href="#guilt" data-toggle="tab" id="guilt-tab">Guilt</a></li>
        <li><a href="#agitation" data-toggle="tab" id="agitation-tab">Agitation</a></li>
    </ul>
    {% if desktop %}
    <div class="tab-content">
        <div class="tab-pane active" id="all">
            <div id='mobile_emotion_chart' class="hidden"></div>
            <div id='emotion_chart'></div>
        </div>
        <div class="tab-pane" id="pain">
            <div id='pain_chart'></div>
        </div>
        <div class="tab-pane" id="sadness">
            <div id='sad_chart'></div>
        </div>
        <div class="tab-pane" id="shame">
            <div id='shame_chart'></div>
        </div>
        <div class="tab-pane" id="anger">
            <div id='anger_chart'></div>
        </div>
        <div class="tab-pane" id="fear">
            <div id='fear_chart'></div>
        </div>
        <div class="tab-pane" id="disgust">
            <div id='disgust_chart'></div>
        </div>
        <div class="tab-pane" id="jealousy">
            <div id='jealousy_chart'></div>
        </div>
        <div class="tab-pane" id="guilt">
            <div id='guilt_chart'></div>
        </div>
        <div class="tab-pane" id="agitation">
            <div id='agitation_chart'></div>
        </div>
    </div>
    {% else %}
    <div class="tab-content">
        <div class="tab-pane active" id="all">
            <div id='mobile_emotion_chart' class="hidden-desktop"></div>
            <div id='emotion_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="pain">
            <div id='pain_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="sadness">
            <div id='sad_chart'class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="shame">
            <div id='shame_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="anger">
            <div id='anger_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="fear">
            <div id='fear_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="disgust">
            <div id='disgust_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="jealousy">
            <div id='jealousy_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="guilt">
            <div id='guilt_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="agitation">
            <div id='agitation_chart' class="visible-desktop"></div>
        </div>
    </div>
    {% endif %}
    <h4 class="heading">Positive Emotions</h4>
    {% if desktop %}
    <ul class="nav nav-tabs" id="pos_emotion_tabs">
    {% else %}
    <ul class="nav nav-tabs visible-desktop" id="pos_emotion_tabs">
    {% endif %}
        <li><a href="#pos_all" data-toggle="tab">All</a></li>
        <li><a href="#joy" data-toggle="tab" id="joy-tab">Joy</a></li>
        <li><a href="#happy" data-toggle="tab" id="happy-tab">Happiness</a></li>
        <li><a href="#content" data-toggle="tab" id="content-tab">Contentment</a></li>
        <li><a href="#calm" data-toggle="tab" id="calm-tab">Calm</a></li>
        <li><a href="#grateful" data-toggle="tab" id="grateful-tab">Grateful</a></li>
        <li><a href="#excitement" data-toggle="tab" id="excitement-tab">Excitement</a></li>
        <li><a href="#optimism" data-toggle="tab" id="optimism-tab">Optimism</a></li>
        <li><a href="#hope" data-toggle="tab" id="hope-tab">Hope</a></li>
        <li><a href="#confidence" data-toggle="tab" id="confidence-tab">Confidence</a></li>
    </ul>
    {% if desktop %}
    <div class="tab-content">
        <div class="tab-pane active" id="pos_all">
            <div id='mobile_pos_emotion_chart' class="hidden"></div>
            <div id='pos_emotion_chart'></div>
        </div>
        <div class="tab-pane" id="joy">
            <div id='joy_chart'></div>
        </div>
        <div class="tab-pane" id="happy">
            <div id='happy_chart'></div>
        </div>
        <div class="tab-pane" id="content">
            <div id='content_chart'></div>
        </div>
        <div class="tab-pane" id="calm">
            <div id='calm_chart'></div>
        </div>
        <div class="tab-pane" id="grateful">
            <div id='grateful_chart'></div>
        </div>
        <div class="tab-pane" id="excitement">
            <div id='excitement_chart'></div>
        </div>
        <div class="tab-pane" id="optimism">
            <div id='optimism_chart'></div>
        </div>
        <div class="tab-pane" id="hope">
            <div id='hope_chart'></div>
        </div>
        <div class="tab-pane" id="confidence">
            <div id='confidence_chart'></div>
        </div>
    </div>
    {% else %}
    <div class="tab-content">
        <div class="tab-pane active" id="pos_all">
            <div id='mobile_pos_emotion_chart' class="hidden-desktop"></div>
            <div id='pos_emotion_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="joy">
            <div id='joy_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="happy">
            <div id='happy_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="content">
            <div id='content_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="calm">
            <div id='calm_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="grateful">
            <div id='grateful_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="excitement">
            <div id='excitement_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="optimism">
            <div id='optimism_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="hope">
            <div id='hope_chart' class="visible-desktop"></div>
        </div>
        <div class="tab-pane" id="confidence">
            <div id='confidence_chart' class="visible-desktop"></div>
        </div>
    </div>
    {% endif %}
    {% else %}
    <p>No diaries to display!</p>
    {% endif %}

dbtdiary/templates/diary/contact.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="heading">Contact Us</h2>
    
    <div class="row">
    	<div class="span8">
    	<div class="well">
        <form action="/contact/" method="post">{% csrf_token %}
            {{ form.non_field_errors }}
            <div class="fieldWrapper">
                {{ form.subject.errors }}
                <label for="id_subject">Subject:</label>
                {{ form.subject }}
            </div>
            <div class="fieldWrapper">
                {{ form.sender.errors }}
                <label for="id_sender">Your email address:</label>
                {{ form.sender }}
            </div>
            
            <div class="fieldWrapper">
                {{ form.message.errors }}
                <label for="id_message">Your message:</label>
                {{ form.message }}
            </div>
            
            <div class="fieldWrapper" id="ccWrapper">
                {{ form.cc_myself.errors }}
                <label for="id_cc_myself">Send a copy to yourself?
                {{ form.cc_myself }}</label>
                <div class="clearfix"></div>
            </div>
            <p><input type="submit" class="btn btn-inverse" value="Send message" /></p>
        </form>
        </div>
        </div>
    </div>
{% endblock %}

dbtdiary/templates/diary/delete-confirm.html
{% extends "base.html" %}

{% block content %}
<h2 class="deck">Really delete diary entry  ID# {{ diary }}, from {{ diary.time }}?</h2>

<form class="wide" action="." method="post">
  {% csrf_token %}
  <p class="submit"><input type="submit" value="Yes, delete the diary."></p>
</form>
{% endblock %}

dbtdiary/templates/diary/index.html
{% extends 'base.html' %}

{% block content %}

	{% if user.is_authenticated %}
	
	<h2 class="heading">Welcome, {{user.username}}.</h2>
    
    <div class="row">
    
    <div class="span5">
    <div class="well">	
    	<h3 class="heading">What would you like to do?</h3>
      <a class="btn btn-large btn-block btn-inverse" href="/submit/">Record a new diary</a>
      <a class="btn btn-large btn-block btn-inverse" href="/summary/" >View past week's diary statistics</a>
      <a class="btn btn-large btn-block btn-inverse" href="/summary/month/" >View past month's diary statistics</a>
      <a class="btn btn-large btn-block btn-inverse" href="/summary/year/" >View past year's diary statistics</a>
      <a class="btn btn-large btn-block btn-inverse" href="/browse/" >Browse previous diaries</a>
    </div>
    </div>
    
    <div class="span7">
    <div class="well">
    <h3 class="heading">Recent Diaries</h3>
   	<table class="table table-hover">
   		<thead>
        <tr>
          <th>Weekday</th>
          <th>Date</th>
          <th>Time</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
   	{% for diary in diaries %}
   	    <tr>
   	    	<td><a href="/diary/{{diary.id}}">{{diary.time|date:"l"}}</a></td>
   	    	<td><a href="/diary/{{diary.id}}">{{diary.time|date:"F jS, Y"}}</a></td>
   	    	<td><a href="/diary/{{diary.id}}">{{diary.time|date:"g:i a"}}</a></td>
          <td><a href="/edit/{{diary.id}}"><i class="icon-edit"></i></a></td>
          <td><a href="/delete/{{diary.id}}"><i class="icon-trash"></i></a></td>
   	    </tr>
   	{% empty %}
   	    <tr>No previous diaries. You should <a href="/submit">fill one out</a>?</tr>
   	{% endfor %}
   	</tbody>
   	</table>
   	</div> 
    </div>
    
	</div><!-- .row -->
	
	{% endif %}
{% endblock %}

dbtdiary/templates/diary/month_summary.html
{% extends 'base.html' %}

{% block header %}

    {% include "diary/charts_js.html" %}

{% endblock %}

{% block content %}   
    <h2 class="heading">Past Month's Summary</h2>
    {% if not desktop %}
    <div class="btn hidden-desktop"><a href="/summary/month?type=desktop">View Desktop Version</a></div>
    {% endif %}
    {% include "diary/charts.html" %}
    
{% endblock %}